export const moods = [
  [
    ["Enraged", "#ca0813"],
    ["Panicked", "#ca0813"],
    ["Stressed", "#de6769"],
    ["Jittery", "#e99a9a"],
    ["Shocked", "#f3cccd"],
    ["Surprised", "#fdf2ce"],
    ["Upbeat", "#fbe49e"],
    ["Festive", "#f9d86f"],
    ["Exhilarated", "#fcf337"],
    ["Ecstatic", "#fcf337"],
  ],
  [
    ["Livid", "#ca0913"],
    ["Furious", "#ca0913"],
    ["Frustrated", "#de6769"],
    ["Tense", "#e99a9a"],
    ["Stunned", "#f3cccd"],
    ["Hyper", "#fdf2ce"],
    ["Cheerful", "#fbe49e"],
    ["Motivated", "#f9d86f"],
    ["Inspired", "#fcf337"],
    ["Elated", "#fcf337"],
  ],
  [
    ["Fuming", "#de6769"],
    ["Frightened", "#de6769"],
    ["Angry", "#de6769"],
    ["Nervous", "#e99a9a"],
    ["Restless", "#f3cccd"],
    ["Energized", "#fdf2ce"],
    ["Lively", "#fbe49e"],
    ["Excited", "#f9d86f"],
    ["Optimistic", "#f9d86f"],
    ["Enthusiastic", "#f9d86f"],
  ],
  [
    ["Anxious", "#e99a9a"],
    ["Apprehensive", "#e99a9a"],
    ["Worried", "#e99a9a"],
    ["Irritated", "#e99a9a"],
    ["Annoyed", "#f3cccd"],
    ["Pleased", "#fdf2ce"],
    ["Focused", "#fbe49e"],
    ["Happy", "#fbe49e"],
    ["Proud", "#fbe49e"],
    ["Thrilled", "#fbe49e"],
  ],
  [
    ["Repulsed", "#f3cccd"],
    ["Troubled", "#f3cccd"],
    ["Concerned", "#f3cccd"],
    ["Uneasy", "#f3cccd"],
    ["Peeved", "#f3cccd"],
    ["Pleasant", "#fdf2ce"],
    ["Joyful", "#fdf2ce"],
    ["Hopeful", "#fdf2ce"],
    ["Playful", "#fdf2ce"],
    ["Blissful", "#fdf2ce"],
  ],
  [
    ["Disgusted", "#cadbf7"],
    ["Glum", "#cadbf7"],
    ["Disappointed", "#cadbf7"],
    ["Down", "#cadbf7"],
    ["Apathetic", "#cadbf7"],
    ["At Ease", "#dae9d4"],
    ["Easygoing", "#dae9d4"],
    ["Content", "#dae9d4"],
    ["Loving", "#dae9d4"],
    ["Fulfilled", "#dae9d4"],
  ],
  [
    ["Pessimistic", "#a5c3f2"],
    ["Morose", "#a5c3f2"],
    ["Discouraged", "#a5c3f2"],
    ["Sad", "#a5c3f2"],
    ["Bored", "#cadbf7"],
    ["Calm", "#dae9d4"],
    ["Secure", "#9eb893"],
    ["Satisfied", "#9eb893"],
    ["Grateful", "#9eb893"],
    ["Touched", "#9eb893"],
  ],
  [
    ["Alienated", "#6fa0e9"],
    ["Miserable", "#6fa0e9"],
    ["Lonely", "#6fa0e9"],
    ["Disheartened", "#a5c3f2"],
    ["Tired", "#cadbf7"],
    ["Relaxed", "#dae9d4"],
    ["Chill", "#9eb893"],
    ["Restful", "#94c380"],
    ["Blessed", "#94c380"],
    ["Balanced", "#94c380"],
  ],
  [
    ["Despondent", "#407bd5"],
    ["Depressed", "#407bd5"],
    ["Sullen", "#6fa0e9"],
    ["Exhausted", "#a5c3f2"],
    ["Fatigued", "#cadbf7"],
    ["Mellow", "#dae9d4"],
    ["Thoughtful", "#9eb893"],
    ["Peaceful", "#94c380"],
    ["Comfortable", "#6ca754"],
    ["Carefree", "#6ca754"],
  ],
  [
    ["Despairing", "#407bd5"],
    ["Hopeless", "#407bd5"],
    ["Desolate", "#6fa0e9"],
    ["Spent", "#a5c3f2"],
    ["Drained", "#cadbf7"],
    ["Sleepy", "#dae9d4"],
    ["Complacent", "#9eb893"],
    ["Tranquil", "#94c380"],
    ["Cozy", "#6ca754"],
    ["Serene", "#6ca754"],
  ],
];
